

build: false

environment:
  matrix:
    - PYTHON_INSTALL: "C:\\Python35"
    - PYTHON_INSTALL: "C:\\Python36"

install:
  - set PATH=%PYTHON_INSTALL%;%PATH%
  - set PATH=%PYTHON_INSTALL%\Scripts;%PATH%
  - python --version
  - pip --version
  - pip install pylint
  - pylint --version

test_script:
  - pylint main.py
  
  

