

build: false

environment:
  matrix:
    - PYTHON: "C:\\Python36-x64"

install:
  - set PATH=%PYTHON_INSTALL%;%PATH%
  - set PATH=%PYTHON_INSTALL%\Scripts;%PATH%
  - dir
  - python --version
  - pip --version
  - pip install pylint
  - pylint --version

test_script:
  - pylint main.py
  
  

