
build: false

environment:
  matrix:
    - PYTHON: "C:\\Python36"
      PYTHON_VERSION: "3.6.4"
      PYTHON_ARCH: "64"

configuration: Release

init:
  - cmd: ver
  - cmd: ECHO Processor architecture - %PROCESSOR_ARCHITECTURE%
  - cmd: wmic OS get OSArchitecture

  # As AppVeyor has multiple python install, check which one uses by default
  - cmd: ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%
  - cmd: set PATH=%PYTHON%;%PYTHON%\scripts;%PATH%
  - cmd: python --version

  # Verify the new default python
  - cmd: python --version
  - cmd: pip --version
  - pip install pylint
  - pylint --version

test_script:
  - pylint main.py
  
  

