

build: false

environment:
  matrix:
    - PYTHON: "C:\\Python36-x64"

install:
  - set PATH=%PYTHON_INSTALL%;%PATH%
  - set PATH=%PYTHON_INSTALL%\Scripts;%PATH%
  - python3 --version
  - pip3 --version
  - pip3 install pylint
  - pylint --version

test_script:
  - pylint main.py
  
  

