build: false

environment:
  matrix:
    - PYTHON: "C:\\Python36"
      PYTHON_VERSION: "3.6.4"
      PYTHON_ARCH: "64"

init:
  - cmd: set PATH=%PYTHON%;%PYTHON%\scripts;%PATH%
  - cmd: python --version
  - cmd: pip --version
  - cmd: pip install pylint
  - cmd: pip install cx_Freeze
  - cmd: pip freeze

test_script:
  # - pylint %APPVEYOR_BUILD_FOLDER%

build_script:
  - cmd: python setup.py build
